[package]
name = "kernel-notify"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
reqwest = {version="0.12.7", features=["blocking"]}
serde = {version="1.0.209", features=["derive"]}
serde_json = "1.0.127"
